artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Aditya151196/datasets/raw/refs/heads/main/summarizer-data.zip
  local_data_file_path: artifacts/data_ingestion/data.zip
  unzip_dir_path: artifacts/data_ingestion